app_name = "awesome web"

# possible values: DEBUG, INFO, WARNING, ERROR, FATAL
log_level = "DEBUG"

[mysql]
ip = "127.0.0.1"
port = 3306
user = "root"
password = "123456"
database = "ramsey"

[redis]
ip = "127.0.0.1"
port = 7381
